title: Lonewolf313s Title
author: Lonewolf313
email: Lonewolf313@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This is my awesome new blog site for the github tutoril "My first week on GitHub"

# social links
twitter_username: Lonewolf313 # DO NOT include the @ character, or else the build will fail!
github_username:  Lonewolf313 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
them: minima
